name: CI
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
    
concurrency: build

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: mvn dependency:copy-dependencies
